config/routes.rb
Rails.application.routes.draw do
  resources :shippingorders
  devise_for :users
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home" 
   match '/home' , to: 'static_pages#home', via: 'get'
   match '/whoweare' , to: 'static_pages#whoweare', via: 'get'
   match '/whatwedo' , to: 'static_pages#whatwedo', via: 'get'
   match '/aboutcompany' , to: 'static_pages#aboutcompany', via: 'get'
   match '/ourceo' , to: 'static_pages#ourceo', via: 'get'
   match '/contactus', to: 'static_pages#contactus', via: 'get'
   match '/timber', to: 'static_pages#timber', via: 'get'
   match '/cashew', to: 'static_pages#cashew', via: 'get'
   match '/yellowcorn', to: 'static_pages#yellowcorn', via: 'get'
   match '/othergoods', to: 'static_pages#othergoods', via: 'get'
   match '/shipmenttracking', to: 'static_pages#shipmenttracking', via: 'get'
   match '/clearingandfowarding', to: 'static_pages#clearingandfowarding', via: 'get'
   match '/generalgoods', to: 'static_pages#generalgoods', via: 'get'
   match '/transportation', to: 'static_pages#transportation', via: 'get'
   match '/vehicletracking', to: 'static_pages#vehicletracking', via: 'get'
   match '/travelpolicy', to: 'static_pages#travelpolicy', via: 'get'
   match '/visaacquisition', to: 'static_pages#visaacquisition', via: 'get'
   match '/passportacquisition', to: 'static_pages#passportacquisition', via: 'get'
   match '/workpermits', to: 'static_pages#workpermits', via: 'get'
   match '/admindashboard', to: 'static_pages#admindashboard', via: 'get'
   post 'findshippingorder' =>'shippingorders#findshippingorder', :as => 'findshippingorder'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/shippingorder.rb
class Shippingorder < ApplicationRecord
	before_create :generate_ourref
	belongs_to :user

	def generate_ourref
       self.ourref = rand(1000011..9900099).to_s 
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shippingorders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phonenumber, :servicetype, :message)
    end
end

app/controllers/shippingorders_controller.rb
class ShippingordersController < ApplicationController
  before_action :set_shippingorder, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token,
                   :if => Proc.new { |c| c.request.format == 'application/json' }
  protect_from_forgery with: :null_session

  # GET /shippingorders
  # GET /shippingorders.json
  def index
    @shippingorders = Shippingorder.all
    @search = Shippingorder.ransack(params[:q])
    @shippingorders = @search.result
  end

  # GET /shippingorders/1
  # GET /shippingorders/1.json
  def show
  end

  # GET /shippingorders/new
  def new
    @shippingorder = Shippingorder.new
  end

  # GET /shippingorders/1/edit
  def edit
  end

  def findshippingorder
    containerno = params[:containerno]
    containernoupcase = containerno.upcase
    containerstrip = containernoupcase.split.join
    @shippingorder = Shippingorder.find_by_containerno(containerstrip)
    if @shippingorder.nil?
        respond_to do |format|
          format.html { redirect_to :back, alert: 'Sorry. Receipt does not exist or your container number is wrong.' }
        end
    else
        respond_to do |format|
          format.html { redirect_to @shippingorder, notice: 'Your Receipt here please.' }
        end
    end
  end

  # POST /shippingorders
  # POST /shippingorders.json
  def create
    @shippingorder = Shippingorder.new(shippingorder_params)
    @shippingorder.user = current_user

    respond_to do |format|
      if @shippingorder.save
        format.html { redirect_to @shippingorder, notice: 'Shippingorder was successfully created.' }
        format.json { render :show, status: :created, location: @shippingorder }
      else
        format.html { render :new }
        format.json { render json: @shippingorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shippingorders/1
  # PATCH/PUT /shippingorders/1.json
  def update
    respond_to do |format|
      if @shippingorder.update(shippingorder_params)
        format.html { redirect_to @shippingorder, notice: 'Shippingorder was successfully updated.' }
        format.json { render :show, status: :ok, location: @shippingorder }
      else
        format.html { render :edit }
        format.json { render json: @shippingorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shippingorders/1
  # DELETE /shippingorders/1.json
  def destroy
    @shippingorder.destroy
    respond_to do |format|
      format.html { redirect_to shippingorders_url, notice: 'Shippingorder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shippingorder
      @shippingorder = Shippingorder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shippingorder_params
      params.require(:shippingorder).permit(:ourref, :fromcomp, :yourref, :shippingline, :containerno, :isocode, :festatus, :sealno, :blno, :drivername, :trucknumber, :driverid, :truckcompany, :condition, :user_id, :gate)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def home
	
end

def whoweare
	
end

def whatwedo
	
end

def aboutcompany
	
end

def ourceo
	
end

def contactus
	@contact = Contact.new
end

def timber
	
end

def cashew
	
end

def yellowcorn
	
end

def othergoods
	
end

def shipmenttracking
	
end

def clearingandfowarding
	
end

def generalgoods
	
end

def transportation
	
end

def vehicletracking
	
end

def travelpolicy
	
end

def visaacquisition
	
end

def passportacquisition
	
end

def workpermits
	
end

def admindashboard
	@q = Shippingorder.ransack(params[:q])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def generate_qr(text)
	  require 'barby'
	  require 'barby/barcode'
	  require 'barby/barcode/qr_code'
	  require 'barby/outputter/png_outputter'

	  barcode = Barby::QrCode.new(text, level: :q, size: 5)
	  base64_output = Base64.encode64(barcode.to_png({ xdim: 5 }))
	  "data:image/png;base64,#{base64_output}"
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/shippingorders_helper.rb
module ShippingordersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phonenumber %>
    <%= f.text_field :phonenumber %>
  </div>

  <div class="field">
    <%= f.label :servicetype %>
    <%= f.text_field :servicetype %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phonenumber</th>
      <th>Servicetype</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phonenumber %></td>
        <td><%= contact.servicetype %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @contact.phonenumber %>
</p>

<p>
  <strong>Servicetype:</strong>
  <%= @contact.servicetype %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/shippingorders/_form.html.erb
<%= form_for(shippingorder) do |f| %>
  <% if shippingorder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shippingorder.errors.count, "error") %> prohibited this shippingorder from being saved:</h2>

      <ul>
      <% shippingorder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Company Name</label>
    <%= f.text_field :fromcomp, :class => "form-control", :placeholder => "Company Name" %>
  </div>

  <!-- <div class="field">
    <%= f.label :yourref %>
    <%= f.text_field :yourref %>
  </div> -->

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Shipping Line</label>
    <%= f.text_field :shippingline, :class => "form-control", :placeholder => "Shipping Line" %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Container number</label>
    <%= f.text_field :containerno, :class => "form-control", :placeholder => "Container number" %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">ISO code</label>
    <%= f.text_field :isocode, :class => "form-control", :placeholder => "ISO code" %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">FE status</label>
    <%= f.text_field :festatus, :class => "form-control", :placeholder => "FE status" %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Seal number</label>
    <%= f.text_field :sealno, :class => "form-control", :placeholder => "Seal no." %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">B/L number</label>
    <%= f.text_field :blno, :class => "form-control", :placeholder => "B/L no." %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Driver name</label>
    <%= f.text_field :drivername, :class => "form-control", :placeholder => "Driver name" %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Truck Number</label>
    <%= f.text_field :trucknumber, :class => "form-control", :placeholder => "Truck Number" %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Driver ID</label>
    <%= f.text_field :driverid, :class => "form-control", :placeholder => "Driver ID" %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Truck Company</label>
    <%= f.text_field :truckcompany, :class => "form-control", :placeholder => "Truck Company" %>
  </div>

  <div class="form-group">
    <label style="font-size: 13px; font-weight: 600;">Condition</label>
    <%= f.text_field :condition, :class => "form-control", :placeholder => "Condition" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/shippingorders/edit.html.erb
<h1>Editing Shippingorder</h1>

<%= render 'form', shippingorder: @shippingorder %>

<%= link_to 'Show', @shippingorder %> |
<%= link_to 'Back', shippingorders_path %>

app/views/shippingorders/index.html.erb
<style type="text/css">
  a {
    color: blue;
  }

  a:hover {
    color: blue;
  }
</style>


<div class="container">
  <div class="row">
    <a href="/admindashboard" class="btn btn-dark printbtn" style="margin-top: 30px;">Go Back</a>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-12">

        <h4>Search Results</h4>
        
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>From</th>
                <th>Container no.</th>
                
                
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @shippingorders.each do |shippingorder| %>
                <tr>
                  <td><%= shippingorder.fromcomp %></td>
                  <td><%= shippingorder.containerno %></td>
                  
                  
                  <td><%= link_to 'Show', shippingorder %></td>
                  <td><%= link_to 'Edit', edit_shippingorder_path(shippingorder) %></td>
                  <td><%= link_to 'Destroy', shippingorder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
        </div>

        <br>
    </div>
  </div>
</div>

app/views/shippingorders/new.html.erb
<div class="container" style="margin-top: 40px;">
	<div class="row">
		<div class="col-lg-6">
			<h4>Create Shipping Receipt</h4>
			<hr>
			<%= render 'form', shippingorder: @shippingorder %>
		</div>
	</div>
</div>

app/views/shippingorders/show.html.erb
<style type="text/css">
  @media print {
         .navbar {
          display: none;
         }

         .footerhide {
          display: none;
         }

         .copyrightfooter {
          display: none;
         }

         .holdit {
          display: none;
         }

         .printbtn {
          display: none;
         }
      }

      p {
        margin-bottom: 0px;
      }

      .whatsapp{
        display: none;
        color: #1DC143;
      }

      .whatsapp:hover, .whatsapp:focus{
        background: #1DC143;
        color: #fff;
        text-shadow: 0 0 1px rgba(0,0,0,0.2);
      }

      .whatsapp.activeWhatsapp{
        display: inline-block;
      }


</style>


<div class="container" id="content">
  <div class="row">
    <% if user_signed_in? %>
    <a href="/admindashboard" class="btn btn-dark printbtn" style="margin-top: 30px;">Go Back</a>
    <% end %>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <p style="text-align: center;">
        <img src="https://nikasemo-static.s3-us-west-2.amazonaws.com/felisco-sun/feliscoslogoweb.png" style="height: 80px; width: 109px; margin-right:0px;">
      </p>
      <h3 style="text-align: center; text-transform: uppercase;">Felisco-Sun Ghana Limited</h3>
      <p style="text-align: center; text-transform: uppercase; font-size: 16px;">
        Tema Community 4, Felisco-Sun Ghana, P.O.Box 8, Tema, Ghana
      </p>
      <p style="text-align: center; font-size: 12px;">
        <span style="font-weight: 600;">Tel.</span> +233(0)248238541; +233(0)262129553 <span style="font-weight: 600;"> Email.</span> info@feliscosunghana.com <span style="font-weight: 600;"> Website.</span> www.feliscosunghana.com
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <p style="text-align: center; font-size: 25px; font-weight: 700; margin-top: 30px; text-transform: uppercase;">
        Shipping Order Receipt
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="rholder">
        <hr style="background-color: #000000;">
        <div class="row">
          <div class="col-lg-6 col-6">
             GATE IN<br><br>
            <p>
              <strong>Our ref:</strong>
              <%= @shippingorder.ourref %>
            </p>
            <p>
              <strong>From:</strong>
              <%= @shippingorder.fromcomp %>
            </p>
          </div>
          <div class="col-lg-6 col-6">
            <p>
              <strong>Date:</strong>
              <%= @shippingorder.created_at.strftime("%B %d, %Y") %>
            </p>
            <p>
              <strong>From:</strong>
              <%= @shippingorder.shippingline %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="rholder">
        <hr style="background-color: #000000;">
        <div class="row">
          <div class="col-lg-6 col-6">
           <p>
              <strong>Container No.:</strong>
              <%= @shippingorder.containerno %>
            </p>
            <p>
              <strong>ISO code:</strong>
              <%= @shippingorder.isocode %>
            </p>
          </div>
          <div class="col-lg-6 col-6">
            <p>
              <strong>FE Status:</strong>
              <%= @shippingorder.festatus %>
            </p>
            <p>
              <strong>Seal No(s):</strong>
              <%= @shippingorder.sealno %>
            </p>
            <p>
              <strong>B/L No:</strong>
              <%= @shippingorder.blno %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="rholder">
        <hr style="background-color: #000000;">
        <div class="row">
          <div class="col-lg-6 col-6">
            <p>
              <strong>Driver name:</strong>
              <%= @shippingorder.drivername %>
            </p>
            <p>
              <strong>Truck No.:</strong>
              <%= @shippingorder.trucknumber %>
            </p>
          </div>
          <div class="col-lg-6 col-6">
            <p>
              <strong>Driver ID:</strong>
              <%= @shippingorder.driverid %>
            </p>
            <p>
              <strong>From:</strong>
              <%= @shippingorder.truckcompany %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="rholder">
         <hr style="background-color: #000000;">
        <p>
          <strong><u>DAMAGE REPORT/INSPECTION REPORT</u></strong>
        </p>
        <p> 
          <%= @shippingorder.condition %>
        </p>
        <p style="text-align: right;">
          <%= image_tag(generate_qr("https://feliscosunghana.com/shippingorders/" + @shippingorder.id.to_s), :class => "qr-code") %>
        </p>
        <% if user_signed_in? %>
        <button class="printbtn" onclick="window.print();">Print</button>
        <!-- <a href= "whatsapp://send?text=https://feliscosunghana.com<%= @shippingorder.id %>"
        data-action="share/whatsapp/share"
        target="_blank" style="color: blue;"> 
        Share to whatsapp 
    </a>  -->
        <!-- <a alt="Whatsapp" href="whatsapp://send" data-text="Text to share" data-href="https://feliscosunghana.com/<%= @shippingorder.id %>" class="whatsapp wa_btn"><span class="ion-social-whatsapp"></span> Whatsapp</a> -->
        <a href="https://wa.me/?text=https://feliscosunghana.com/shippingorders/<%= @shippingorder.id %>" class="btn btn-success printbtn" target="_blank"><i class="fa fa-whatsapp" aria-hidden="true"></i> Share to Whatsapp</a>
        <button class="printbtn" id="cmd">Generate PDF</button>
        <% end %>
        <br><br><br>
      </div>
    </div>
  </div>
</div>
<div id="editor"></div>

<script type="text/javascript">
  var doc = new jsPDF();
    var specialElementHandlers = {
        '#editor': function (element, renderer) {
            return true;
        }
    };

    $('#cmd').click(function () {
        doc.fromHTML($('#content').html(), 15, 15, {
            'width': 170,
                'elementHandlers': specialElementHandlers
        });
        doc.save('sample-file.pdf');
    });
</script>

app/views/static_pages/admindashboard.html.erb
<style type="text/css">
	.holddashboardhead {
		background-color: #eaeaea;
		padding-top: 50px;
		padding-bottom: 50px;
		padding-left: 20px;
		padding-right: 20px;
		border-radius: 30px;
	}
</style>

<br>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="holddashboardhead">
				<h1 style="text-align: center;">Welcome</h1>
				<p style="text-align: center;">Welcome to the admin dashboard. Manage The Felisco-Sun Ghana Ltd. from here.</p>
			</div>
		</div>
	</div>
	<div class="row" style="margin-top: 20px;">
		<div class="col-lg-12">
			<p style="text-align: center;">
				<a href="/shippingorders/new" class="btn btn-primary">Create Shipping Order</a>
			</p>
		</div>
		<!-- <div class="col-lg-6">
			
		</div> -->
	</div>
	<div class="row" style="margin-top: 20px; margin-bottom: 40px;">
		<div class="col-lg-4">
			<h5>Shipping Orders</h5>
			<div class="row">
				<% Shippingorder.all.each do |shippingorder| %>
				<div class="col-lg-12">
					<p style="border-bottom: 1px solid #aeaeae; padding-bottom: 10px;">
						<%= shippingorder.fromcomp %><br>
						<%= shippingorder.containerno %><br>
						<% if shippingorder.user.present? %>
						<span style="font-size: 10px;">Created by: <%= shippingorder.user.email %> </span><br><br>
						<% end %>
						<a href="/shippingorders/<%= shippingorder.id %>" style="color: blue;">Shipping details</a>
					</p>

				</div>
				<% end %>
			</div>
		</div>

		<div class="col-lg-4">
			<h5>Client Request</h5>
			<div class="row">
			<% Contact.all.each do |contact| %>
					<div class="col-lg-12">
						<p>
					<%= contact.name %><br>
					<a href="/contacts/<%= contact.id %>">Read Requests</a>
					</p>
					</div>

				<% end %>
			</div>
		</div>

		<div class="col-lg-4">
			<%= search_form_for @q do |f| %>
          <div class="row no-gutters">
             <div class="col-lg-8">
              <%= f.search_field :containerno_cont, :placeholder =>"Container Number", :class => "form-control" %>
            </div>
            <div class="col-lg-4">
              <button style="margin-left: 10px;" class="btn btn-primary">Find</button>
            </div>
          </div>
          <% end %>
		</div>
	</div>
</div>

app/views/static_pages/whoweare.html.erb
<style type="text/css">
  
.howbintrot {
  background-color: #0290fd;
  color: #ffffff;
  padding: 20px;
  font-size: 14px;
  font-weight: 500;
}

.actnowbutton {
  background-color: #ffffff;
  border: 1px solid #ffffff;
  border-radius: 0px;
  color: #4a4a4a;
  font-size: 18px;
  font-weight: 500;
}

.actnowbutton:hover {
  background-color: #ffffff;
  border: 1px solid #ffffff;
  border-radius: 20px;
  color: #4a4a4a;
  font-size: 18px;
  font-weight: 700;
}

.actnowbutton:active {
  background-color: #ffffff;
  border: 1px solid #ffffff;
  border-radius: 20px;
  color: #4a4a4a;
  font-size: 18px;
  font-weight: 700;
}

.ctasection {
  background-color: #0290fd;
  padding: 30px;
}

</style>


<section class="my-5" id="sect2">
  <div class="container">
    <div class="row">

      <div class="col-lg-6">

        <h4 style="color: #0290fd; font-family: 'Francois One', sans-serif; margin-bottom: 20px;">Who we are</h4>

            <p class="howbintrot">Felisco-Sun Ghana Limited is your reliable and most efficient provider of freight forwarding and total logistics services.</p>

            <p style="font-size: 14px; line-height: 28px;">
            Felisco-Sun Ghana Limited is your reliable and most efficient provider of freight forwarding and total logistics services.<br>
            With international and local branches, we employ both full time and casual staff in order to facilitate smooth running of our entire product portfolio value chain. We have been operating since 2012 and our experience with hundreds of clients makes us the best partner for all your freight forwarding and logistics services. We employ international best practices both in dealing with customers as well as our staff. Our work philosophy focus on the positivity of life, thus our logo bearing the sun as array of hope and life each day we see it.<br>
            We truly believe that whenever the sun shines on the surface of the earth we will endeavor to reach it on behalf of our clients.
            </p>
		        
      </div>

      <div class="col-lg-6">
        
        		<p>
             <img class="img-fluid" src="https://nikasemo-static.s3-us-west-2.amazonaws.com/felisco-sun/5f4db88dc6353-welc.jpg"></p>
       
      </div>

    </div>
  </div>
</section>

<section class="ctasection">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">

        <div class="holdcta">
          
          <p style="text-align: left; font-size: 14px; line-height: 20px; color: #ffffff; font-weight: 400; margin-top: 10px;">
            <span style="font-weight: 600; font-size: 18px;">Click on the button on your right and start talking to us.</span></p>
          
        </div>
        
      </div>
      <div class="col-lg-4">
        <p style="text-align: center;">
          <a href="/contactus" class="btn btn-primary btn-lg actnowbutton" data-toggle="modal" data-target="#exampleModal">Work with Us</a>
        </p>
      </div>

    </div>
  </div>
</section>